/**
 * Build-time loaders for knowledge-compiler artifacts.
 *
 * The portal is a static Next.js export (no server at request time per D3).
 * These helpers read the compiler's JSON output from `public/artifacts/`
 * during `next build` — the same moment the markdown is compiled. The result
 * is inlined into the page HTML, so it works with JS disabled and needs no
 * runtime fetch or database.
 *
 * Artifacts are regenerated by `knowledge-compiler/run.py` (prebuild). If they
 * are missing (e.g. running the site without a prebuild), every loader degrades
 * gracefully to `null` / empty so the site still renders.
 */
import fs from 'fs';
import path from 'path';

const ARTIFACTS_DIR = path.join(process.cwd(), 'public', 'artifacts');

export type ArtifactStatus = 'observed' | 'designed' | 'proposed' | 'experiment';

export interface ArtifactIndexPost {
  slug: string;
  title: string;
  author: string;
  date: string;
  canonical_url: string;
  status: ArtifactStatus;
  topics: string[];
  series: string | null;
  featured: boolean;
  content_hash: string;
}

export interface ArtifactIndex {
  schema_version: number;
  generated_at: string;
  compiler: string;
  total: number;
  posts: ArtifactIndexPost[];
}

export interface GraphNode {
  id: string;
  label: string;
  type: 'article' | 'entity';
  slug?: string;
  status?: string;
  topics?: string[];
  date?: string;
  featured?: boolean;
}

export interface GraphEdge {
  from: string;
  to: string;
  label: string;
  weight: number;
  basis: string;
}

export interface GraphJson {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export interface SearchEntry {
  slug: string;
  title: string;
  excerpt: string;
  tokens: string[];
}

export interface SearchJson {
  engine: string;
  k1: number;
  b: number;
  entries: SearchEntry[];
}

export interface Relationship {
  type: string;
  target: string;
  weight: number;
  basis: string;
}

export interface Claim {
  text: string;
  confidence: number | null;
  evidence_refs: string[];
}

export interface Provenance {
  source: string;
  compiler: string;
  compiler_version: number;
  model_version: number | null;
  content_sha256: string;
  generated_at: string;
}

export interface Sidecar {
  schema_version: number;
  id: string;
  title: string;
  author: string;
  created_at: string;
  updated_at: string;
  canonical_url: string;
  content_hash: string;
  topics: string[];
  status: ArtifactStatus;
  series: string | null;
  entities: string[];
  relationships: Relationship[];
  claims: Claim[];
  references: string[];
  related_artifacts: string[];
  provenance: Provenance;
  publication_status?: string;
}

function readJsonSafe<T>(file: string): T | null {
  try {
    const full = path.join(ARTIFACTS_DIR, file);
    if (!fs.existsSync(full)) return null;
    return JSON.parse(fs.readFileSync(full, 'utf-8')) as T;
  } catch {
    return null;
  }
}

let _indexCache: ArtifactIndex | null | undefined;
let _graphCache: GraphJson | null | undefined;
let _searchCache: SearchJson | null | undefined;

export function getArtifactIndex(): ArtifactIndex | null {
  if (_indexCache === undefined) _indexCache = readJsonSafe<ArtifactIndex>('index.json');
  return _indexCache;
}

export function getGraph(): GraphJson | null {
  if (_graphCache === undefined) _graphCache = readJsonSafe<GraphJson>('graph.json');
  return _graphCache;
}

export function getSearchIndex(): SearchJson | null {
  if (_searchCache === undefined) _searchCache = readJsonSafe<SearchJson>('search.json');
  return _searchCache;
}

export function getSidecar(slug: string): Sidecar | null {
  return readJsonSafe<Sidecar>(`${slug}.json`);
}

/** Fast lookup map: slug -> index entry. */
export function getArtifactIndexMap(): Map<string, ArtifactIndexPost> {
  const idx = getArtifactIndex();
  const map = new Map<string, ArtifactIndexPost>();
  if (idx) for (const p of idx.posts) map.set(p.slug, p);
  return map;
}

/** Build a slug -> related-slug[] map from graph "related" edges (article<->article). */
export function getRelatedMap(): Map<string, string[]> {
  const graph = getGraph();
  const map = new Map<string, string[]>();
  if (!graph) return map;
  for (const edge of graph.edges) {
    if (edge.label !== 'related') continue;
    if (!edge.from.startsWith('post:') || !edge.to.startsWith('post:')) continue;
    const a = edge.from.slice(5);
    const b = edge.to.slice(5);
    if (!map.has(a)) map.set(a, []);
    if (!map.has(b)) map.set(b, []);
    map.get(a)!.push(b);
    map.get(b)!.push(a);
  }
  return map;
}
