import type { Sidecar } from '@/lib/artifacts';
import { TopicChip } from './TopicChip';

/**
 * Glass provenance panel. Reads the compiled sidecar for a post and shows the
 * epistemic metadata: content hash (sha256), compiler version, topics, entities,
 * and the build timestamp. This is the "signed artifact" surface — it makes the
 * build provenance visible. Server-rendered; no client JS.
 */
export function ProvenancePanel({ sidecar }: { sidecar: Sidecar | null }) {
  if (!sidecar) return null;

  const shortHash = sidecar.content_hash.replace(/^sha256:/, '').slice(0, 16);

  return (
    <aside className="border border-[var(--color-rule)] bg-[var(--color-glass-bg)] p-6">
      <div className="flex items-center gap-2 mb-5">
        <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-green)]" />
        <h2 className="font-mono text-[0.62rem] tracking-[0.16em] uppercase text-[var(--color-ink-3)]">Artifact Provenance</h2>
      </div>

      <dl className="space-y-4 text-sm">
        <div>
          <dt className="font-mono text-[0.58rem] tracking-[0.14em] uppercase text-[var(--color-ink-3)] mb-1">Content Hash (sha256)</dt>
          <dd className="font-mono text-[0.7rem] text-[var(--color-ink)] break-all bg-[var(--color-paper-2)] px-2 py-1 border border-[var(--color-rule)]">
            {shortHash}…
          </dd>
        </div>

        <div>
          <dt className="font-mono text-[0.58rem] tracking-[0.14em] uppercase text-[var(--color-ink-3)] mb-1">Compiler</dt>
          <dd className="font-mono text-[0.7rem] text-[var(--color-ink)]">{sidecar.provenance.compiler}</dd>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <dt className="font-mono text-[0.58rem] tracking-[0.14em] uppercase text-[var(--color-ink-3)] mb-1">Compiled</dt>
            <dd className="font-mono text-[0.7rem] text-[var(--color-ink)]">
              {new Date(sidecar.provenance.generated_at).toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'short',
                day: 'numeric',
              })}
            </dd>
          </div>
          <div>
            <dt className="font-mono text-[0.58rem] tracking-[0.14em] uppercase text-[var(--color-ink-3)] mb-1">Status</dt>
            <dd className="font-mono text-[0.7rem] text-[var(--color-ink)] capitalize">{sidecar.status}</dd>
          </div>
        </div>

        {sidecar.topics.length > 0 && (
          <div>
            <dt className="font-mono text-[0.58rem] tracking-[0.14em] uppercase text-[var(--color-ink-3)] mb-2">Topics</dt>
            <dd className="flex flex-wrap gap-1.5">
              {sidecar.topics.slice(0, 8).map((t) => (
                <TopicChip key={t} topic={t} />
              ))}
            </dd>
          </div>
        )}

        {sidecar.entities.length > 0 && (
          <div>
            <dt className="font-mono text-[0.58rem] tracking-[0.14em] uppercase text-[var(--color-ink-3)] mb-2">Entities ({sidecar.entities.length})</dt>
            <dd className="flex flex-wrap gap-1.5">
              {sidecar.entities.slice(0, 10).map((e) => (
                <span
                  key={e}
                  className="font-mono text-[0.58rem] px-1.5 py-0.5 border border-[var(--color-rule)] text-[var(--color-ink-3)]"
                >
                  {e}
                </span>
              ))}
            </dd>
          </div>
        )}
      </dl>

      <p className="mt-5 font-mono text-[0.58rem] text-[var(--color-ink-3)] leading-relaxed">
        Generated by the knowledge-compiler at build time. Reproducible from source — same
        markdown yields the same hash.
      </p>
    </aside>
  );
}
